### ISSUE TITLE
Improve existing find command

### ISSUE THREAD

**Issue by lycjackie** [CS2113-AY1819S2-T09-1/main#65]
`Find` command exists in the original AB4, however, the find was only 
limited to a person `name`.

After morphing into our application. Being able to find a module's
name is not sufficient enough for our target users.

I propose that we improve on the existing `FindCommand` to allow
the finding of module's `name`, `code`, `credits` and `tags` and:
- [x] able to search for multiple keywords in each attribute
i.e. `find code/CODE CODE CODE CODE`
returns modules having its code matches any of the keywords given
- [x] able to include multiple attributes in one `FindCommand`
i.e. `find name/NAME code/CODE`
returns module having its name or code matches the keyword given
- [x] able to specify boolean logic conditions in the `FindCommand`
i.e. `find name/NAME && code/CODE` 
returns module having its name and code matches the keywords given
- [x] able to handle brackets via intuitive input.
i.e. `find code/CODE || (name/NAME && name/NAME)`

These changes will provide the user with a more flexible way of 
finding the module they need.

**Comment by Creastery** [comment]
Closing in view of PR #119, which addresses the above.
