### ISSUE TITLE
Feedback on week 8 project progress

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S2-T09-1/main#74]
Subject: feedback on week 8 project progress

See [mid-v1.2 progress guide](https://nuscs2113-ay1819s2.github.io/website/admin/project-w08-mid-v12.html) for more details of the activities mentioned below.
***Mid-milestone progress reports are FYI only. They are not graded.***

### Recommended progress for the upcoming milestone

-  [x]  Issue labels<sup>*</sup> set up e.g., `type.*` and `priority.*` (:heavy_check_mark: well done!)
-  [x]  All future milestones `v1.2`, `v1.3`, `v1.4`, created (:heavy_check_mark: well done!)
-  [x]  Issues marked as `type.Story` e.g., [link](https://github.com/CS2113-AY1819S2-T09-1/main/issues/66) (:heavy_check_mark: well done!)
-  [x]  Some issues prioritized using `priority.*` labels e.g., [link](https://github.com/CS2113-AY1819S2-T09-1/main/issues/11) (:heavy_check_mark: well done!)
*  Milestone v1.2 planned
     -  [x]  A suitable deadline<sup>**</sup> set (:heavy_check_mark: well done!)
     -  [x]  Issues allocated to v1.2 e.g., [link](https://github.com/CS2113-AY1819S2-T09-1/main/issues/63) (:heavy_check_mark: well done!)
-  [x]  Build passing [link](https://travis-ci.org/CS2113-AY1819S2-T09-1/main/builds/501555299) (:heavy_check_mark: well done!)

 <sup>*</sup>Remember to use the format specified, else it will not be picked up by the bot
<sup>**</sup>Remember that the deadline is the midnight before your tutorials

### Recommended progress for the upcoming milestone

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the next milestone (:heavy_check_mark: well done!)

### Follow up from v1.1

* Used forking workflow:
     -  [x]  Created PRs [link](https://github.com/CS2113-AY1819S2-T09-1/main/pull/59) (:heavy_check_mark: well done!)
     -  [x]  Gave review comments to other PRs (:exclamation: try to do by next milestone)

- [x]  Merged updates to documents (:exclamation: try to do by next milestone)
- [x]  `wendybaiyunwei.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:heavy_check_mark: well done!)

### Recommended progress for the upcoming milestone

  - [x]  Merged updates to java/fxml files (:exclamation: try to do by next milestone)
  - [x]  Has issues/PRs assigned for the next milestone (:exclamation: try to do by next milestone)

### Recommended progress for the upcoming milestone

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the next milestone (:heavy_check_mark: well done!)

### Recommended progress for the upcoming milestone

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the next milestone (:heavy_check_mark: well done!)

### Recommended progress for the upcoming milestone

  - [x]  Merged updates to java/fxml files (:exclamation: try to do by next milestone)
  - [x]  Has issues/PRs assigned for the next milestone (:heavy_check_mark: well done!)

Tutor: @sanjukta99

Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-03-12 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.

**Comment by chyeo** [comment]
@sanjukta99 @cs2113-feedback-bot @okkhoy
Greetings, I believe there is an error with the results for the checks as some PRs made by me have already been merged in such as PR #43. 
Additionally, I have also merged in PRs made by my groupmates such as PR #27 

Have listed both PRs as the definition of 'merge' in this context was rather vague.
