### ISSUE TITLE
As a user, I want to be able to classify modules under different requirement categories.

### ISSUE THREAD

**Issue by chyeo** [CS2113-AY1819S2-T09-1/main#95]
To allow users to be able to classify modules based on the different requirement categories.

The following function that allow users to interact with the requirement categories needs to be implemented:

- [x] able to add modules into the requirement category
- [x] able to remove modules from the requirement category
- [x] able to list the entire requirement category
- [x] able to move the module from one requirement category to another requirement category

**Comment by Creastery** [comment]
Closing this in view of #171.
