### ISSUE TITLE
As a user, I want to see specific degree planner(s).

### ISSUE THREAD

**Issue by Letm3through** [CS2113-AY1819S2-T09-1/main#96]
The user may want to see the degree planners based on certain condition.
Hence, I propose implementing ```planner_show``` command as follows with/without Boolean expression:
- [x] able to show degree planner(s) by year
i.e. `planner_show year/YEAR`
returns academic semester(s) having its year matches the year given
- [x] able to show degree planner(s) by semester
i.e. `planner_show sem/SEMESTER`
returns academic semester(s) having its semester matches the semester given
- [x] able to include both `year` and `semester` attributes in one `planner_show` command
i.e. `planner_show year/YEAR && sem/SEMESTER`
returns academic semester(s) having its year and semester matches the given year and semester
- [x] able to include both `year` and `semester` attributes  with more complex Boolean expression in one `planner_show` command
i.e. `planner_show year/YEAR && ( sem/SEMESTER || sem/SEMESTER)`
returns academic semester(s) having its year and semester satisfies the Boolean expression 

These sub-features will allow the user to only see his/her degree planner(s) that he/she wants.

**Comment by Creastery** [comment]
As discussed, let's reduce the priority of this feature since the UI reflects all the year/semesters in the degree plan already. This is a nice to have feature.
